"""Shared flash geometry used by packaging and generated firmware definitions."""

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
LAYOUT_PATH = ROOT / "config/flash_layout.json"
HEADER_PATH = ROOT / "config/flash_layout.h"


def load_layout(path=LAYOUT_PATH):
    layout = json.loads(Path(path).read_text(encoding="utf-8"))
    if (layout["flash_base"] != 0x10000000 or layout["flash_size"] != 0x200000
            or layout["page_size"] != 256 or layout["sector_size"] != 4096):
        raise ValueError("layout must describe the qualified original Pico 2 MiB geometry")
    names, macros = set(), set()
    end = 0
    for part in layout["partitions"]:
        offset, size = part["offset"], part["size"]
        if type(offset) is not int or type(size) is not int:
            raise ValueError("partition addresses and sizes must be integers")
        if offset < end or size <= 0 or offset % 4096 or size % 4096:
            raise ValueError("partitions must be ordered, disjoint and sector aligned")
        end = offset + size
        if end > layout["flash_size"]:
            raise ValueError("partition exceeds physical flash")
        if part["name"] in names or part["macro"] in macros:
            raise ValueError("duplicate partition name or macro")
        if not re.fullmatch(r"SLOT_[A-Z0-9_]+", part["macro"]):
            raise ValueError("invalid partition macro")
        if type(part["executable"]) is not bool:
            raise ValueError("executable must be boolean")
        names.add(part["name"])
        macros.add(part["macro"])
    if names != {"bootloader", "config", "config_backup", "cmsis_dap", "blackmagic", "picorvd"}:
        raise ValueError("layout must contain the supervisor, two configuration sectors and all three modes")
    parts = {p["name"]: p for p in layout["partitions"]}
    if parts["bootloader"]["offset"] != 0:
        raise ValueError("supervisor must start at flash base")
    if any(p["executable"] != (p["name"] not in ("config", "config_backup")) for p in parts.values()):
        raise ValueError("only configuration sectors may be non-executable")
    if parts["config"]["size"] != 4096 or parts["config_backup"]["size"] != 4096:
        raise ValueError("each configuration journal sector must be exactly 4096 bytes")
    return layout


def render_header(layout):
    lines = ["/* Generated by tools/flash_layout.py; edit flash_layout.json. */",
             "#ifndef FLASH_LAYOUT_H", "#define FLASH_LAYOUT_H", "",
             f'#define FLASH_BASE_ADDR (0x{layout["flash_base"]:08X}U)',
             f'#define FLASH_TOTAL_SIZE (0x{layout["flash_size"]:08X}U)', ""]
    for part in layout["partitions"]:
        macro = part["macro"]
        lines += [f'#define {macro}_OFFSET (0x{part["offset"]:08X}U)',
                  f'#define {macro}_ADDR (FLASH_BASE_ADDR + {macro}_OFFSET)',
                  f'#define {macro}_SIZE (0x{part["size"]:08X}U)', ""]
    return "\n".join(lines + ["#endif /* FLASH_LAYOUT_H */", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated header is stale")
    args = parser.parse_args()
    expected = render_header(load_layout())
    if args.check:
        if not HEADER_PATH.exists() or HEADER_PATH.read_text(encoding="utf-8") != expected:
            print("flash_layout.h is stale; run python3 tools/flash_layout.py", file=sys.stderr)
            return 1
    else:
        HEADER_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
